name: AI Code Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Trigger AI Review
        run: |
          curl -X POST "http://your-api-endpoint/review_pr" \
               -H "Content-Type: application/json" \
               -d '{"repo_owner": "${{ github.repository_owner }}", "repo_name": "${{ github.event.repository.name }}", "pr_number": ${{ github.event.pull_request.number }} }'
